#网关
version: '3'
services:

  #网关服务
  library-gateway-web:
    image: worklog/library-gateway-web:latest
    container_name: library-gateway-web
    restart: always
    networks:
      - sc-net
    ports:
      - 8443:8443
    env_file: .env
    environment:
      TZ: Asia/Shanghai

  #网关管理服务
  library-gateway-admin:
    image: worklog/library-gateway-admin:latest
    container_name: library-gateway-admin
    restart: always
    networks:
      - sc-net
    ports:
      - 8445:8445
    env_file: .env
    environment:
      TZ: Asia/Shanghai
