#网关
version: '3'
services:

  #library-gateway-admin Mysql数据库初使化
  library-gateway-admin-db-init:
    image: mysql-init-db:latest
    networks:
      - sc-net
    volumes:
      - ../library-gateway/library-gateway-admin/src/main/db:/sql
     # - ./init-db.sh:/usr/bin/init-db.sh
    environment:
      MYSQL_ROOT_PASSWORD: root123
   # entrypoint: /usr/bin/init-db.sh
    #command: ping 0.0.0.0


  #网关服务
  library-gateway-web:
    image: worklog/library-gateway-web:latest
    container_name: sc-library-gateway-web
    restart: always
    networks:
      - sc-net
    ports:
      - 8443:8443
    env_file: .env
    environment:
      TZ: Asia/Shanghai

  #网关管理服务
  library-gateway-admin:
    image: worklog/library-gateway-admin:latest
    container_name: sc-library-gateway-admin
    restart: always
    networks:
      - sc-net
    ports:
      - 8445:8445
    env_file: .env
    environment:
      TZ: Asia/Shanghai
