version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: sc-redis
    restart: always
    volumes:
      - ../data/redis:/data
    environment:
      - REDIS_PASSWORD=123456
    networks:
      - sc-net
    ports:
      - 6379:6379
    env_file: .env

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: sc-rabbitmq
    restart: always
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - sc-net
    ports:
      - 5672:5672
      - 15672:15672
    env_file: .env

  mysql:
    image: mysql:5.7
    container_name: sc-mysql
    restart: always
    networks:
      - sc-net
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root123

  mysql-init:
    image: mysql-init-db:latest
    networks:
      - sc-net
    volumes:
      - ./db/library-auth:/sql/library-auth
      - ./db/library-gateway-admin:/sql/library-gateway-admin
      - ./db/service-organization:/sql/service-organization
    environment:
      MYSQL_ROOT_PASSWORD: root123

  postgres:
    restart: always
    networks:
      - sc-net
    image: postgres:9.6.2
    container_name: sc-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata

networks:
  sc-net:
    external: false