version: '3'
services:
  library-register-nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    networks:
      - sc-net
    volumes:
      - ../data/nacos-server/logs/:/home/nacos/logs
      - ./config/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"

  devops-prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - sc-net
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - library-register-nacos
    restart: on-failure