#授权，认证，组织 三个服务服务，重要必须
version: '3'
services:
  #授权服务
  library-authorization-server:
    image: worklog/library-authorization-server:latest
    container_name: library-authorization-server
    restart: always
    networks:
      - sc-net
    ports:
      - 8000:8000
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - library-authentication-server

  #认证服务
  library-authentication-server:
    image: worklog/library-authentication-server:latest
    container_name: library-authentication-server
    restart: always
    networks:
      - sc-net
    ports:
      - 8001:8001
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - service-organization

  #组织服务
  service-organization:
    image: worklog/service-organization:latest
    container_name: service-organization
    restart: always
    networks:
      - sc-net
    ports:
      - 8010:8010
    env_file: .env
    environment:
      TZ: Asia/Shanghai

networks:
  sc_net:
    external: false